server:
  port: 1304

spring:
  application:
    name: shop
  profiles:
    active: local
  main:
    allow-bean-definition-overriding: true
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
  jpa:
    show-sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://iqsbz-test.cmzny3nijw9z.ap-northeast-2.rds.amazonaws.com:3306/iqsbz3?serverTimezone=UTC
    username: iqsbz
    password: '!SqiSoft00'
#    maximum-pool-size: 1
#    connection-test-query: SELECT 1
#    idle-timeout: 100000
#    validation-timeout: 3000
#    max-lifetime: 180000
  output:
    ansi:
      enabled: always

logging:
  level:
    org.springframework.web.client: DEBUG
    org.hibernate.type: trace
    com.zaxxer.hikari: DEBUG
    org.hibernate: DEBUG
    org.hibernate.event: ERROR
    org.hibernate.engine: ERROR
